export const quesionsArray = [
  {
    key: 0,
    ques: "01-Example of sementic HTML?",
    options: ["div", "span", "header", "img"],
    ans: "header",
    attempted: null,
    flagged: true,
  },
  {
    key: 1,
    ques: "02-Difference javascript and react?",
    options: ["library", "tool", "langauge", "db"],
    ans: "library",
    attempted: null,
    flagged: true,
  },
  {
    key: 2,
    ques: "03-Which database follow ACID property?",
    options: ["mySql", "mongoDB", "redis", "dynomoDB"],
    ans: "mySql",
    attempted: null,
    flagged: true,
  },
  {
    key: 3,
    ques: "04-Example Example Example?",
    options: ["div", "span", "header", "img"],
    ans: "header",
    attempted: null,
    flagged: true,
  },
  {
    key: 4,
    ques: "05-New question of javascript?",
    options: ["div", "span", "header", "img"],
    ans: "header",
    attempted: null,
    flagged: true,
  },
];
